mysql:
  host: 127.0.0.1
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/mydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
