mysql:
  host: 192.168.102.136
  port: 32768

nacos:
  server-address: 192.168.102.138
  port: 8848
  username: nacos
  password: nacos

sqlserver:
  host: 10.211.55.5
  port: 1433
  db: mydb
  user: sa
  password: wqd@1994

server:
  port: 3001

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/seata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: admin
            login-password: admin
          filter:
            stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
            wall:
              config:
                multi-statement-allow: true
          aop-patterns: site.paranoia.account.service.*.*
        fin:
          url: jdbc:sqlserver://192.168.100.101:1433;databasename=cmlfincen
          username: cmlfin
          password: fincen@cmlog
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          connectionErrorRetryAttempts: 0
          breakAfterAcquireFailure: true
          stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: admin
            login-password: admin
          filter:
            stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
            wall:
              config:
                multi-statement-allow: true
          aop-patterns: site.paranoia.account.service.*.*
      primary: fin
      seata: true
      seata-mode: AT
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-address}:${nacos.port}
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-group
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: site.paranoia.account.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}&subscribe=false
  cloud:
    subscribed-services:

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: ${nacos.server-address}:${nacos.port}
      group: SEATA_GROUP
      userName: ${nacos.username}
      password: ${nacos.password}
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.server-address}:${nacos.port}
      namespace:
      userName: ${nacos.username}
      password: ${nacos.password}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
