mysql:
  host: 192.168.102.136
  port: 32768

nacos:
  server-address: 192.168.102.138
  port: 8848
  username: nacos
  password: nacos

server:
  port: 3001

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/seata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
      primary: master
      seata: true
      seata-mode: at
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-address}:${nacos.port}
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-group
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: site.paranoia.account.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: ${nacos.server-address}:${nacos.port}
      group: SEATA_GROUP
      userName: ${nacos.username}
      password: ${nacos.password}
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.server-address}:${nacos.port}
      namespace:
      userName: ${nacos.username}
      password: ${nacos.password}
