mysql:
  host: 192.168.102.136
  port: 32768

nacos:
  address: 192.168.102.138:8848

server:
  port: 3001

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/seata?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-group
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: site.paranoia.account.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.address}

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: ${nacos.address}
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.address}
      namespace:
      userName: "nacos"
      password: "nacos"
