mysql:
  host: 192.168.102.136
  port: 32768


spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/paranoia-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  type-aliases-package: site.paranoia.domain
#  mapper-locations: classpath:mapper/*.xml
#
#mapper:
#  mappers:
#    - site.paranoia.utils.MyMapper
#  not-empty: false
#  identity: MYSQL
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


